# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1253, 908)
        self.qlabel = QtWidgets.QLabel(widget)
        self.qlabel.setGeometry(QtCore.QRect(40, 40, 1171, 841))
        self.qlabel.setText("")
        self.qlabel.setObjectName("qlabel")
        self.datelabel = QtWidgets.QLabel(widget)
        self.datelabel.setGeometry(QtCore.QRect(220, 50, 741, 121))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.datelabel.setFont(font)
        self.datelabel.setStyleSheet("background: transparent;")
        self.datelabel.setText("")
        self.datelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.datelabel.setObjectName("datelabel")
        self.futureedit = QtWidgets.QTextEdit(widget)
        self.futureedit.setGeometry(QtCore.QRect(810, 260, 351, 551))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.futureedit.setFont(font)
        self.futureedit.setStyleSheet("background-color: transparent;\n"
"border:none;")
        self.futureedit.setObjectName("futureedit")
        self.weatheredit = QtWidgets.QTextEdit(widget)
        self.weatheredit.setGeometry(QtCore.QRect(60, 180, 411, 451))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.weatheredit.setFont(font)
        self.weatheredit.setStyleSheet("background-color: transparent;\n"
"border:none;")
        self.weatheredit.setObjectName("weatheredit")
        self.comboBox = QtWidgets.QComboBox(widget)
        self.comboBox.setGeometry(QtCore.QRect(960, 90, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "camera"))
        self.comboBox.setItemText(0, _translate("widget", "眼镜一"))
        self.comboBox.setItemText(1, _translate("widget", "眼镜二"))
        self.comboBox.setItemText(2, _translate("widget", "眼镜三"))
