# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1107, 740)
        Form.setStyleSheet("background-color: rgba(255, 255, 255, 60);")
        self.widget = QCameraViewfinder(Form)
        self.widget.setGeometry(QtCore.QRect(11, 11, 1085, 718))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.currentedit = QtWidgets.QTextEdit(self.widget)
        self.currentedit.setGeometry(QtCore.QRect(40, 100, 271, 541))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.currentedit.setFont(font)
        self.currentedit.setStyleSheet("background-color: transparent;\n"
"border:none;")
        self.currentedit.setObjectName("currentedit")
        self.foreedit = QtWidgets.QTextEdit(self.widget)
        self.foreedit.setGeometry(QtCore.QRect(690, 120, 371, 561))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.foreedit.setFont(font)
        self.foreedit.setStyleSheet("background-color: transparent;\n"
"border:none;")
        self.foreedit.setObjectName("foreedit")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(360, 30, 691, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;\n"
"border:none;")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "camera"))
from PyQt5.QtMultimediaWidgets import QCameraViewfinder
